return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "html",
      "lua",
      "dockerfile",
      "tsx",
      "css",
      "vim",
      "luadoc",
      "markdown",
      "markdown_inline",
      "python",
      "ruby",
      "rust",
      "go",
      "cmake",
      "make",
      "json",
      "toml",
      "yaml",
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { "ruby" },
    },
    indent = { enable = true, disable = { "ruby" } },
  },
}
